#!/bin/bash
mkdir -p temp_out
make
for file in ../tests/*.in; do
	NR=`echo $file | grep -o [0-9]`
	./crystals < $file > "temp_out/test$NR.out"
	DIFF=`diff "../tests/t$NR.out" "temp_out/test$NR.out" `
	if [ -z "$DIFF" ]; then
		echo "OK - $NR"
	else
		echo "ERROR - $NR"
	fi
done
